version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  subsequent_positive_tests:
    run: python:latest python analysis/subsequent_positive_tests.py
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        graph1: output/repeated_positive_date.svg
        graph2: output/interval_between_positives.svg

